FROM node:14

WORKDIR /app

COPY user.js .
COPY wait-for-it.sh .
RUN chmod +x wait-for-it.sh
RUN npm install express ws dotenv

EXPOSE 9303

CMD ["./wait-for-it.sh", "postgres:5432", "--timeout=30", "--", "./wait-for-it.sh", "rabbitmq:5672", "--timeout=30", "--", "node", "user.js"]
